SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET VERIFY OFF

DECLARE
    PI CONSTANT NUMBER(3,2) := 3.14;
    R NUMBER(5);
    CIRCUMFERENCE NUMBER(7,2);

BEGIN
    R := &R;

    DBMS_OUTPUT.PUT_LINE('CIRCUMFERENCE OF CIRCLE');
    DBMS_OUTPUT.PUT_LINE('=======================');

    CIRCUMFERENCE := 2 * PI * R;

    DBMS_OUTPUT.PUT_LINE('Radius = ' || R);
    DBMS_OUTPUT.PUT_LINE('Circumference of Circle = ' || CIRCUMFERENCE);
    DBMS_OUTPUT.PUT_LINE('=======================');
END;
/

SET SERVEROUTPUT OFF
SET FEEDBACK ON
SET VERIFY ON