SET SERVEROUTPUT ON;
SET VERIFY OFF;

CREATE OR REPLACE PROCEDURE INCREASE_SALARY
(
    P_DEPTNO  IN EMP2.DEPTNO%TYPE,
    P_PERCENT IN NUMBER
)
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM EMP2
    WHERE DEPTNO = P_DEPTNO;

    IF V_COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(101, 'Department number not found');
    END IF;

    UPDATE EMP2
    SET BASICSAL = BASICSAL + (BASICSAL * P_PERCENT / 100)
    WHERE DEPTNO = P_DEPTNO;

    DBMS_OUTPUT.PUT_LINE('Salary increased successfully');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/

ACCEPT DNO NUMBER PROMPT 'Enter Department No: '
ACCEPT PER NUMBER PROMPT 'Enter Percentage: '

BEGIN
    INCREASE_SALARY(&DNO, &PER);
END;
/